/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light mode colors
        background: "#F8FAFC",
        surface: "#FFFFFF",
        "surface-highlight": "#F1F5F9",
        primary: "#0EA5E9",
        "primary-fg": "#FFFFFF",
        secondary: "#6366F1",
        "secondary-fg": "#FFFFFF",
        success: "#10B981",
        "success-bg": "#ECFDF5",
        warning: "#F59E0B",
        "warning-bg": "#FFFBEB",
        error: "#F43F5E",
        "error-bg": "#FFF1F2",
        "text-main": "#0F172A",
        "text-muted": "#64748B",
        border: "#E2E8F0",
        // High contrast light
        "hc-background": "#000000",
        "hc-surface": "#111827",
        "hc-surface-highlight": "#1F2937",
        "hc-primary": "#FACC15",
        "hc-primary-fg": "#000000",
        "hc-secondary": "#22D3EE",
        "hc-secondary-fg": "#000000",
        "hc-text-main": "#FFFFFF",
        "hc-text-muted": "#E5E7EB",
        "hc-border": "#FACC15",
        // Dark mode color variants
        dark: {
          background: "#0F172A",
          surface: "#1E293B",
          "surface-highlight": "#334155",
          primary: "#38BDF8",
          "primary-fg": "#0F172A",
          secondary: "#818CF8",
          "secondary-fg": "#0F172A",
          success: "#34D399",
          "success-bg": "#064E3B",
          warning: "#FBBF24",
          "warning-bg": "#78350F",
          error: "#FB7185",
          "error-bg": "#881337",
          "text-main": "#F1F5F9",
          "text-muted": "#94A3B8",
          border: "#334155",
          // High contrast dark
          "hc-background": "#000000",
          "hc-surface": "#0B0F1A",
          "hc-surface-highlight": "#111827",
          "hc-primary": "#FACC15",
          "hc-primary-fg": "#000000",
          "hc-secondary": "#22D3EE",
          "hc-secondary-fg": "#000000",
          "hc-text-main": "#FFFFFF",
          "hc-text-muted": "#E5E7EB",
          "hc-border": "#FACC15",
        },
      },
    },
  },
  plugins: [],
}